site_name: My Docs
theme:
  name: dracula
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  logo: "assets/images/kb.png"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ComplexSec
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SecComplex
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jonathan-james-pake/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - nl2br

plugins:
  - search
  - callouts
